bugs:
- head-branch: ['^fix/', '^hotfix/']

ci:
- changed-files:
  - any-glob-to-any-file: ['.github/**/*']
- head-branch: ['^ci/']

deps:
- changed-files:
  - any-glob-to-any-file: ['**/package.json', '**/pyproject.toml']
- head-branch: ['^renovate/']

deploy:
- head-branch: ['^deploy/']

docs:
- changed-files:
  - any-glob-to-any-file: ['**/README.md', '**/CHANGELOG.md']

features:
- head-branch: ['^feat/']

renovate:
- head-branch: ['^renovate/']

schemas:
- changed-files:
  - any-glob-to-any-file: ['schemas/**/*']

tests:
- changed-files:
  - any-glob-to-any-file: ['tests/**/*']
