name: Upload assets to release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-assets:
    strategy:
      matrix:
        builds:
          - os: ubuntu-24.04
            arch: linux-x86_64
          - os: ubuntu-24.04-arm
            arch: linux-aarch64
          - os: macos-14
            arch: darwin-aarch64

    runs-on: ${{ matrix.builds.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build binaries
        run: |
          echo "Compiling echo-server ${{ github.ref_name }} binary for ${{ matrix.builds.arch }} ..."
          gcc -Wall -o echo-server_${{ matrix.builds.arch }}-${{ github.ref_name }} ./echo-server.c

      - name: Generate checksum file
        run: |
          echo "Generating check sum file: echo-server_${{ matrix.builds.arch }}-${{ github.ref_name }}.sha256"
          shasum -a 256 echo-server_${{ matrix.builds.arch }}-${{ github.ref_name }} > echo-server_${{ matrix.builds.arch }}-${{ github.ref_name }}.sha256

      - name: Upload assets to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Uploading assets for echo-server release ${{ github.ref_name }}"

          echo "Uploading binary file: echo-server_${{ matrix.builds.arch }}-${{ github.ref_name }}"
          gh release upload ${{ github.ref_name }} echo-server_${{ matrix.builds.arch }}-${{ github.ref_name }}

          echo "Uploading checksum file: echo-server_${{ matrix.builds.arch }}-${{ github.ref_name }}.sha256"
          gh release upload ${{ github.ref_name }} echo-server_${{ matrix.builds.arch }}-${{ github.ref_name }}.sha256
