name: Stale Image

on:
  schedule:
    # Runs on 19:00 JST every day, note that cron syntax applied as UTC
    - cron: '0 10 * * *'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-24.04
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v2
        with:
          image-names: echo-server
          image-tags: "!latest !main"
          cut-off: 1 days ago JST
          # Keep 1 image within 1 days ago
          keep-at-least: 5
          account-type: personal
          token: ${{ secrets.PAT_PACKAGE_CLEANUP }}
